defmodule PosServerWeb.UserLive do
  use PosServerWeb, :live_view

  alias PosServer.Accounts
  alias PosServer.Accounts.{User, UserToken}

  @impl true
  def mount(_params, _session, socket) do
    {:ok,
     socket
     |> assign_user_form(Accounts.change_user(%User{}))
     |> assign_company_form(Accounts.change_company(%PosServer.Accounts.Company{}))
     |> assign_token_form(Accounts.change_user_token(%UserToken{}, %{"context" => "session"}))
     |> assign(:users, Accounts.list_users())
     |> assign(:status, nil)}
  end

  @impl true
  def handle_event("save_user", %{"user" => user_attrs, "company" => company_attrs}, socket) do
    case Accounts.create_company_user(user_attrs, company_attrs) do
      {:ok, user} ->
        {:noreply,
         socket
         |> assign_user_form(Accounts.change_user(%User{}))
         |> assign_company_form(Accounts.change_company(%PosServer.Accounts.Company{}))
         |> assign(:users, Accounts.list_users())
         |> assign(:status, "User #{user.email}, tenant #{user.tenant}, and company created.")}

      {:error, :user, changeset} ->
        {:noreply, assign_user_form(socket, changeset)}

      {:error, :company, changeset} ->
        {:noreply, assign_company_form(socket, changeset)}

      {:error, :tenant, reason} ->
        {:noreply, assign(socket, :status, "Tenant setup failed: #{format_tenant_error(reason)}")}
    end
  end

  def handle_event("save_token", %{"user_token" => attrs}, socket) do
    case Accounts.create_user_token(attrs) do
      {:ok, _token} ->
        {:noreply,
         socket
         |> assign_token_form(Accounts.change_user_token(%UserToken{}, %{"context" => "session"}))
         |> assign(:status, "Session token created. The token value is not displayed.")}

      {:error, changeset} ->
        {:noreply, assign_token_form(socket, changeset)}
    end
  end

  @impl true
  def render(assigns) do
    ~H"""
    <section aria-labelledby="user-token-title">
      <div class="card">
        <div class="card-header">
          <h1 class="card-title" id="user-token-title">Users</h1>
          <p class="card-description">Create users and issue their session tokens.</p>
        </div>
        <div class="card-content">
          <p :if={@status} role="status" class="field-description"><%= @status %></p>

          <div class="form">
            <h2>Current users</h2>
            <p :if={@users == []} class="field-description">No users yet.</p>
            <div :for={user <- @users} class="form-field">
              <strong><%= user.name %></strong>
              <span class="field-description"><%= user.email %></span>
              <span class="field-description">Tenant: <%= user.tenant %></span>
              <code><%= user.id %></code>
            </div>
          </div>

          <form class="form" phx-submit="save_user">
            <h2>Create company user</h2>
            <.field field={@user_form[:name]} label="Name" type="text" required />
            <.field field={@user_form[:email]} label="Email" type="email" required />
            <.field field={@user_form[:password]} label="Password" type="password" required />
            <.field field={@user_form[:tenant]} label="Tenant ID" type="text" required />
            <p class="field-description">Use lowercase letters, numbers, and underscores (for example, <code>acme_store</code>).</p>
            <h3>Company</h3>
            <.field field={@company_form[:company_name]} label="Company name" type="text" required />
            <.field field={@company_form[:rnc]} label="RNC" type="text" />
            <div class="form-actions">
              <button class="btn" data-variant="default" type="submit">Create user and company</button>
            </div>
          </form>

          <form class="form" phx-submit="save_token">
            <h2>Create session token</h2>
            <p class="field-description">Paste the user ID from the list. Tokens are generated by the server and use the <code>session</code> context.</p>
            <.field field={@token_form[:user_id]} label="User ID" type="text" required />
            <div class="form-actions">
              <button class="btn" data-variant="default" type="submit">Create session token</button>
            </div>
          </form>
        </div>
      </div>
    </section>
    """
  end

  attr :field, :any, required: true
  attr :label, :string, required: true
  attr :type, :string, required: true
  attr :required, :boolean, default: false

  defp field(assigns) do
    ~H"""
    <div class="form-field" data-invalid={@field.errors != [] || nil}>
      <label class="label" for={@field.id}><%= @label %></label>
      <input
        class="input"
        id={@field.id}
        name={@field.name}
        type={@type}
        value={if @type == "password", do: nil, else: @field.value}
        required={@required}
        autocomplete={if @type == "password", do: "new-password"}
        aria-invalid={if @field.errors == [], do: "false", else: "true"}
      />
      <p :for={{message, _opts} <- @field.errors} class="field-error" role="alert"><%= message %></p>
    </div>
    """
  end

  defp assign_user_form(socket, changeset), do: assign(socket, :user_form, to_form(changeset, as: :user))
  defp assign_company_form(socket, changeset), do: assign(socket, :company_form, to_form(changeset, as: :company))
  defp assign_token_form(socket, changeset), do: assign(socket, :token_form, to_form(changeset, as: :user_token))

  defp format_tenant_error(reason) when is_binary(reason), do: reason
  defp format_tenant_error(_reason), do: "The tenant schema could not be created."
end
