const translations = {
  en: {
    "nav.primary": "Primary navigation", "nav.catalog": "Catalog", "nav.sales": "Sales history", "nav.settings": "Settings", "status.system": "System status", "status.printerChecking": "Checking printer status", "status.networkUnavailable": "Network status unavailable",
    "brand.retail": "Educa retail", "pos.title": "Point of Sale", "search.label": "Search", "search.placeholder": "Search products or scan a barcode", "search.focus": "Focus product search", "language.change": "Change display language", "language.menu": "Language", "catalog.label": "Catalog", "catalog.products": "Products", "products.loading": "Loading products…",
    "order.current": "Current sale", "order.clear": "Clear", "order.empty": "Your order is empty. Select a product to begin.", "total.items": "Items", "total.subtotal": "Subtotal", "total.tax": "Tax (18%)", "total.discount": "Discount", "total.total": "Total", "discount.orderTrigger": "Apply order discount. Double click or press Enter.", "payment.method": "Payment method", "payment.cash": "Cash", "charge": "Charge {amount}",
    "customer.pick": "Pick a customer …", "customer.change": "Change customer", "customer.clear": "Clear customer", "customer.label": "Customers", "customer.list": "Customer list", "customer.create": "Create customer", "customer.createDescription": "Add a customer, then use them on this sale.", "customer.search": "Search customers", "customer.searchPlaceholder": "Search customers by name or phone", "customer.tableCaption": "Choose a customer for this sale.", "customer.name": "Name", "customer.phone": "Phone", "customer.email": "Email", "customer.select": "Select customer", "customer.choose": "Choose", "customer.loading": "Loading customers…", "customer.empty": "No customers found.", "customer.error": "Customers could not be loaded. Check the server connection.", "customer.save": "Save customer", "customer.saveError": "Customer could not be created. Check the details and try again.",
    "discount.line": "Line item discount", "discount.apply": "Apply a discount", "discount.choose": "Choose a percentage for this item.", "discount.type": "Discount type", "discount.percentage": "Percentage discount", "discount.amountOption": "Amount discount", "discount.amount": "Discount amount", "discount.enterItem": "Enter 0 to remove this item discount.", "discount.previewAmount": "Amount", "discount.after": "After discount", "action.cancel": "Cancel", "discount.applyAction": "Apply discount", "clear.title": "Clear this order?", "clear.description": "All items and line discounts will be removed.", "clear.keep": "Keep order", "clear.confirm": "Clear order",
    "product.unnamed": "Unnamed product", "product.add": "Add {name} to order", "product.stock": "{count} in stock", "product.tap": "Tap + to add", "product.emptyMatch": "No matching products.", "product.none": "No active products found.", "product.loadingMore": "Loading more products…", "product.scroll": "Scroll for more products", "product.loaded": "{count} products loaded", "product.error": "Products could not be loaded. Check the server connection.", "printer.connected": "Printer connected", "printer.disconnected": "Printer disconnected", "print.addItem": "Add an item before printing.", "print.printing": "Printing…", "print.error": "Print error: {error}",
    "cart.off": "off", "cart.sub": "Sub", "cart.each": "each", "cart.remove": "Remove {name}", "cart.decrease": "Decrease quantity", "cart.increase": "Increase quantity", "cart.itemCount": "Item count", "cart.removed": "{name} removed", "action.undo": "Undo", "action.back": "Back", "discount.orderActive": "The order discount is active. Set it to 0 before editing item discounts.", "discount.applyOrder": "Apply an order discount", "discount.orderDescription": "This applies to the final order amount and replaces every item discount.", "discount.removedOrder": "Order discount removed", "discount.appliedOrder": "Order discount applied", "discount.resetItems": "Item discounts were reset.", "discount.applied": "Discount applied", "discount.removed": "Discount removed", "discount.percentageLabel": "Discount percentage", "discount.removeOrder": "Enter 0 to remove this order discount.", "discount.orderAmount": "The amount applies to the final order total.", "discount.itemAmount": "The amount applies to this entire line item.", "order.cleared": "Order cleared",
    "checkout.label": "Checkout", "checkout.continue": "Continue", "checkout.backSale": "Back to sale", "checkout.stepCustomer": "1. Customer", "checkout.stepPayment": "2. Payment", "checkout.stepSetup": "3. Final setup", "checkout.stepPay": "4. Pay", "checkout.stepOne": "Step 1 of 4", "checkout.stepTwo": "Step 2 of 4", "checkout.stepThree": "Step 3 of 4", "checkout.stepFour": "Step 4 of 4", "checkout.customer.title": "Select customer", "checkout.customer.empty": "Customer selection will be added here.", "checkout.payment.title": "Payment", "checkout.payment.empty": "Payment options will be added here.", "checkout.setup.title": "Final setup", "checkout.setup.empty": "Final sale settings will be added here.", "checkout.pay.title": "Pay", "checkout.pay.empty": "Choose how to complete this sale.", "checkout.continuePayment": "Continue to payment", "checkout.continueSetup": "Continue to final setup", "checkout.continuePay": "Continue to pay", "checkout.payCredit": "Pay on credit", "checkout.delivery": "Delivery", "checkout.credit": "Pay on Credit", "checkout.sequence": "Sequence type", "checkout.payments": "Payments", "checkout.addPayment": "Add payment", "checkout.complete": "Complete", "checkout.paymentMethod": "Payment method", "checkout.cash": "Cash", "checkout.card": "Credit Card", "checkout.amount": "Amount", "checkout.remaining": "Remaining", "checkout.change": "Change", "checkout.removePayment": "Remove payment", "checkout.customer": "Customer", "checkout.paymentCompletion": "Payment & completion"
  },
  es: {
    "nav.primary": "Navegación principal", "nav.catalog": "Catálogo", "nav.sales": "Historial de ventas", "nav.settings": "Configuración", "status.system": "Estado del sistema", "status.printerChecking": "Comprobando estado de impresora", "status.networkUnavailable": "Estado de red no disponible",
    "brand.retail": "Educa retail", "pos.title": "Punto de venta", "search.label": "Buscar", "search.placeholder": "Busca productos o escanea un código de barras", "search.focus": "Enfocar búsqueda de productos", "language.change": "Cambiar idioma de la interfaz", "language.menu": "Idioma", "catalog.label": "Catálogo", "catalog.products": "Productos", "products.loading": "Cargando productos…",
    "order.current": "Venta actual", "order.clear": "Limpiar", "order.empty": "Tu pedido está vacío. Selecciona un producto para comenzar.", "total.items": "Artículos", "total.subtotal": "Subtotal", "total.tax": "Impuesto (18%)", "total.discount": "Descuento", "total.total": "Total", "discount.orderTrigger": "Aplicar descuento al pedido. Haz doble clic o presiona Intro.", "payment.method": "Método de pago", "payment.cash": "Efectivo", "charge": "Cobrar {amount}",
    "customer.pick": "Elegir un cliente …", "customer.change": "Cambiar cliente", "customer.clear": "Quitar cliente", "customer.label": "Clientes", "customer.list": "Lista de clientes", "customer.create": "Crear cliente", "customer.createDescription": "Añade un cliente y úsalo en esta venta.", "customer.search": "Buscar clientes", "customer.searchPlaceholder": "Busca por nombre o teléfono", "customer.tableCaption": "Elige un cliente para esta venta.", "customer.name": "Nombre", "customer.phone": "Teléfono", "customer.email": "Correo electrónico", "customer.select": "Seleccionar cliente", "customer.choose": "Elegir", "customer.loading": "Cargando clientes…", "customer.empty": "No se encontraron clientes.", "customer.error": "No se pudieron cargar los clientes. Revisa la conexión al servidor.", "customer.save": "Guardar cliente", "customer.saveError": "No se pudo crear el cliente. Revisa los datos e inténtalo de nuevo.",
    "discount.line": "Descuento por artículo", "discount.apply": "Aplicar un descuento", "discount.choose": "Elige un porcentaje para este artículo.", "discount.type": "Tipo de descuento", "discount.percentage": "Descuento porcentual", "discount.amountOption": "Descuento por importe", "discount.amount": "Importe del descuento", "discount.enterItem": "Introduce 0 para quitar este descuento del artículo.", "discount.previewAmount": "Importe", "discount.after": "Después del descuento", "action.cancel": "Cancelar", "discount.applyAction": "Aplicar descuento", "clear.title": "¿Limpiar este pedido?", "clear.description": "Se eliminarán todos los artículos y descuentos por línea.", "clear.keep": "Conservar pedido", "clear.confirm": "Limpiar pedido",
    "product.unnamed": "Producto sin nombre", "product.add": "Añadir {name} al pedido", "product.stock": "{count} en existencia", "product.tap": "Toca + para añadir", "product.emptyMatch": "No hay productos coincidentes.", "product.none": "No se encontraron productos activos.", "product.loadingMore": "Cargando más productos…", "product.scroll": "Desplázate para ver más productos", "product.loaded": "{count} productos cargados", "product.error": "No se pudieron cargar los productos. Revisa la conexión al servidor.", "printer.connected": "Impresora conectada", "printer.disconnected": "Impresora desconectada", "print.addItem": "Añade un artículo antes de imprimir.", "print.printing": "Imprimiendo…", "print.error": "Error de impresión: {error}",
    "cart.off": "de descuento", "cart.sub": "Sub", "cart.each": "c/u", "cart.remove": "Eliminar {name}", "cart.decrease": "Disminuir cantidad", "cart.increase": "Aumentar cantidad", "cart.itemCount": "Cantidad de artículos", "cart.removed": "{name} eliminado", "action.undo": "Deshacer", "action.back": "Atrás", "discount.orderActive": "El descuento del pedido está activo. Establécelo en 0 antes de editar descuentos por artículo.", "discount.applyOrder": "Aplicar un descuento al pedido", "discount.orderDescription": "Se aplica al total final del pedido y reemplaza cada descuento por artículo.", "discount.removedOrder": "Descuento del pedido eliminado", "discount.appliedOrder": "Descuento del pedido aplicado", "discount.resetItems": "Se restablecieron los descuentos por artículo.", "discount.applied": "Descuento aplicado", "discount.removed": "Descuento eliminado", "discount.percentageLabel": "Porcentaje de descuento", "discount.removeOrder": "Introduce 0 para quitar este descuento del pedido.", "discount.orderAmount": "El importe se aplica al total final del pedido.", "discount.itemAmount": "El importe se aplica a toda esta línea de pedido.", "order.cleared": "Pedido limpiado",
    "checkout.label": "Cobro", "checkout.continue": "Continuar", "checkout.backSale": "Volver a la venta", "checkout.stepCustomer": "1. Cliente", "checkout.stepPayment": "2. Pago", "checkout.stepSetup": "3. Configuración final", "checkout.stepPay": "4. Cobrar", "checkout.stepOne": "Paso 1 de 4", "checkout.stepTwo": "Paso 2 de 4", "checkout.stepThree": "Paso 3 de 4", "checkout.stepFour": "Paso 4 de 4", "checkout.customer.title": "Seleccionar cliente", "checkout.customer.empty": "La selección de cliente se añadirá aquí.", "checkout.payment.title": "Pago", "checkout.payment.empty": "Las opciones de pago se añadirán aquí.", "checkout.setup.title": "Configuración final", "checkout.setup.empty": "Los ajustes finales de la venta se añadirán aquí.", "checkout.pay.title": "Cobrar", "checkout.pay.empty": "Elige cómo completar esta venta.", "checkout.continuePayment": "Continuar al pago", "checkout.continueSetup": "Continuar a la configuración final", "checkout.continuePay": "Continuar a cobrar", "checkout.payCredit": "Cobrar a crédito", "checkout.change": "Cambio"
  },
  pt: {
    "nav.primary": "Navegação principal", "nav.catalog": "Catálogo", "nav.sales": "Histórico de vendas", "nav.settings": "Configurações", "status.system": "Status do sistema", "status.printerChecking": "Verificando status da impressora", "status.networkUnavailable": "Status da rede indisponível",
    "brand.retail": "Educa varejo", "pos.title": "Ponto de venda", "search.label": "Pesquisar", "search.placeholder": "Pesquise produtos ou leia um código de barras", "search.focus": "Focar pesquisa de produtos", "language.change": "Alterar idioma da interface", "language.menu": "Idioma", "catalog.label": "Catálogo", "catalog.products": "Produtos", "products.loading": "Carregando produtos…",
    "order.current": "Venda atual", "order.clear": "Limpar", "order.empty": "Seu pedido está vazio. Selecione um produto para começar.", "total.items": "Itens", "total.subtotal": "Subtotal", "total.tax": "Imposto (18%)", "total.discount": "Desconto", "total.total": "Total", "discount.orderTrigger": "Aplicar desconto ao pedido. Clique duas vezes ou pressione Enter.", "payment.method": "Forma de pagamento", "payment.cash": "Dinheiro", "charge": "Cobrar {amount}",
    "customer.pick": "Escolha um cliente …", "customer.change": "Alterar cliente", "customer.clear": "Limpar cliente", "customer.label": "Clientes", "customer.list": "Lista de clientes", "customer.create": "Criar cliente", "customer.createDescription": "Adicione um cliente e use-o nesta venda.", "customer.search": "Pesquisar clientes", "customer.searchPlaceholder": "Pesquise por nome ou telefone", "customer.tableCaption": "Escolha um cliente para esta venda.", "customer.name": "Nome", "customer.phone": "Telefone", "customer.email": "E-mail", "customer.select": "Selecionar cliente", "customer.choose": "Escolher", "customer.loading": "Carregando clientes…", "customer.empty": "Nenhum cliente encontrado.", "customer.error": "Não foi possível carregar os clientes. Verifique a conexão com o servidor.", "customer.save": "Salvar cliente", "customer.saveError": "Não foi possível criar o cliente. Verifique os dados e tente novamente.",
    "discount.line": "Desconto por item", "discount.apply": "Aplicar um desconto", "discount.choose": "Escolha uma porcentagem para este item.", "discount.type": "Tipo de desconto", "discount.percentage": "Desconto percentual", "discount.amountOption": "Desconto por valor", "discount.amount": "Valor do desconto", "discount.enterItem": "Digite 0 para remover o desconto deste item.", "discount.previewAmount": "Valor", "discount.after": "Após o desconto", "action.cancel": "Cancelar", "discount.applyAction": "Aplicar desconto", "clear.title": "Limpar este pedido?", "clear.description": "Todos os itens e descontos por linha serão removidos.", "clear.keep": "Manter pedido", "clear.confirm": "Limpar pedido",
    "product.unnamed": "Produto sem nome", "product.add": "Adicionar {name} ao pedido", "product.stock": "{count} em estoque", "product.tap": "Toque em + para adicionar", "product.emptyMatch": "Nenhum produto correspondente.", "product.none": "Nenhum produto ativo encontrado.", "product.loadingMore": "Carregando mais produtos…", "product.scroll": "Role para ver mais produtos", "product.loaded": "{count} produtos carregados", "product.error": "Não foi possível carregar os produtos. Verifique a conexão com o servidor.", "printer.connected": "Impressora conectada", "printer.disconnected": "Impressora desconectada", "print.addItem": "Adicione um item antes de imprimir.", "print.printing": "Imprimindo…", "print.error": "Erro de impressão: {error}",
    "cart.off": "de desconto", "cart.sub": "Sub", "cart.each": "cada", "cart.remove": "Remover {name}", "cart.decrease": "Diminuir quantidade", "cart.increase": "Aumentar quantidade", "cart.itemCount": "Quantidade de itens", "cart.removed": "{name} removido", "action.undo": "Desfazer", "action.back": "Voltar", "discount.orderActive": "O desconto do pedido está ativo. Defina-o como 0 antes de editar descontos por item.", "discount.applyOrder": "Aplicar um desconto ao pedido", "discount.orderDescription": "Isso se aplica ao valor final do pedido e substitui todos os descontos por item.", "discount.removedOrder": "Desconto do pedido removido", "discount.appliedOrder": "Desconto do pedido aplicado", "discount.resetItems": "Os descontos por item foram redefinidos.", "discount.applied": "Desconto aplicado", "discount.removed": "Desconto removido", "discount.percentageLabel": "Porcentagem de desconto", "discount.removeOrder": "Digite 0 para remover este desconto do pedido.", "discount.orderAmount": "O valor se aplica ao total final do pedido.", "discount.itemAmount": "O valor se aplica a toda esta linha do pedido.", "order.cleared": "Pedido limpo",
    "checkout.label": "Finalização", "checkout.continue": "Continuar", "checkout.backSale": "Voltar à venda", "checkout.stepCustomer": "1. Cliente", "checkout.stepPayment": "2. Pagamento", "checkout.stepSetup": "3. Configuração final", "checkout.stepPay": "4. Pagar", "checkout.stepOne": "Etapa 1 de 4", "checkout.stepTwo": "Etapa 2 de 4", "checkout.stepThree": "Etapa 3 de 4", "checkout.stepFour": "Etapa 4 de 4", "checkout.customer.title": "Selecionar cliente", "checkout.customer.empty": "A seleção de cliente será adicionada aqui.", "checkout.payment.title": "Pagamento", "checkout.payment.empty": "As opções de pagamento serão adicionadas aqui.", "checkout.setup.title": "Configuração final", "checkout.setup.empty": "As configurações finais da venda serão adicionadas aqui.", "checkout.pay.title": "Pagar", "checkout.pay.empty": "Escolha como concluir esta venda.", "checkout.continuePayment": "Continuar para pagamento", "checkout.continueSetup": "Continuar para configuração final", "checkout.continuePay": "Continuar para pagar", "checkout.payCredit": "Pagar a crédito", "checkout.change": "Troco"
  }
};

const LANGUAGE_KEY = "educa-pos-language";
const listeners = new Set();
const browserLanguage = navigator.language.toLowerCase();
let language = localStorage.getItem(LANGUAGE_KEY) || (browserLanguage.startsWith("es") ? "es" : browserLanguage.startsWith("pt") ? "pt" : "en");

export function t(key, values = {}) {
  const template = translations[language]?.[key] ?? translations.en[key] ?? key;
  return template.replace(/\{(\w+)\}/g, (_, name) => values[name] ?? `{${name}}`);
}

export function getLanguage() { return language; }

export function setLanguage(nextLanguage) {
  if (!translations[nextLanguage] || nextLanguage === language) return;
  language = nextLanguage;
  localStorage.setItem(LANGUAGE_KEY, language);
  document.documentElement.lang = language;
  translateDocument();
  listeners.forEach((listener) => listener(language));
}

export function onLanguageChange(listener) { listeners.add(listener); return () => listeners.delete(listener); }

export function translateDocument(root = document) {
  root.querySelectorAll("[data-i18n]").forEach((element) => { element.textContent = t(element.dataset.i18n); });
  root.querySelectorAll("[data-i18n-placeholder]").forEach((element) => { element.placeholder = t(element.dataset.i18nPlaceholder); });
  root.querySelectorAll("[data-i18n-aria-label]").forEach((element) => { element.setAttribute("aria-label", t(element.dataset.i18nAriaLabel)); });
  root.querySelectorAll("[data-i18n-alt]").forEach((element) => { element.alt = t(element.dataset.i18nAlt); });
}

document.documentElement.lang = language;
